services:
  backend:
    image: ${DOCKER_USERNAME}/pos-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '4001:4001'
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-worker:
    image: ${DOCKER_USERNAME}/pos-notification-worker:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    command: redis-server --port 6380 --requirepass ${REDIS_PASSWORD}
    ports:
      - '6380:6380'
    volumes:
      - redis_data:/data
    healthcheck:
      test:
        ['CMD', 'redis-cli', '-p', '6380', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    ports:
      - '5673:5672'
      - '15673:15672'
    environment:
      RABBITMQ_DEFAULT_USER: oakarkyaw
      RABBITMQ_DEFAULT_PASS: oakarkyaw
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  rabbitmq_data:
